create table ingestion_runs (
    id bigint generated by default as identity primary key,
    source_name varchar(64) not null,
    source_update_time timestamptz not null,
    status varchar(32) not null,
    first_seen_at timestamptz not null,
    completed_at timestamptz,
    last_failed_at timestamptz,
    last_error_code varchar(64),
    last_error_retryable boolean,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uq_ingestion_runs_source_update unique (source_name, source_update_time),
    constraint ck_ingestion_runs_status
        check (status in ('DISCOVERED', 'IN_PROGRESS', 'PARTIAL', 'FAILED', 'STAGED')),
    constraint ck_ingestion_runs_failure_complete
        check (
            (last_error_code is null and last_failed_at is null
                and last_error_retryable is null)
            or
            (last_error_code is not null and last_failed_at is not null
                and last_error_retryable is not null)
        ),
    constraint ck_ingestion_runs_status_state
        check (
            (status = 'STAGED' and completed_at is not null
                and last_error_code is null)
            or
            (status = 'DISCOVERED' and completed_at is null
                and last_error_code is null)
            or
            (status in ('FAILED', 'PARTIAL') and completed_at is null
                and last_error_code is not null)
            or
            (status = 'IN_PROGRESS' and completed_at is null)
        )
);

create table ingestion_source_state (
    source_name varchar(64) primary key,
    continuity_baseline timestamptz not null,
    latest_observed_update_time timestamptz not null,
    first_run_policy varchar(16) not null,
    initialized_at timestamptz not null,
    updated_at timestamptz not null,
    constraint ck_ingestion_source_state_policy
        check (first_run_policy in ('LATEST', 'FIXED')),
    constraint ck_ingestion_source_state_order
        check (continuity_baseline <= latest_observed_update_time)
);

create table ingestion_gaps (
    id bigint generated by default as identity primary key,
    source_name varchar(64) not null,
    first_missing_update_time timestamptz not null,
    last_missing_update_time timestamptz not null,
    detected_at timestamptz not null,
    constraint fk_ingestion_gaps_source_state
        foreign key (source_name) references ingestion_source_state (source_name),
    constraint ck_ingestion_gaps_order
        check (first_missing_update_time <= last_missing_update_time),
    constraint uq_ingestion_gaps_range
        unique (source_name, first_missing_update_time, last_missing_update_time)
);

create table ingestion_archives (
    idempotency_key text primary key,
    run_id bigint not null,
    source_update_time timestamptz not null,
    archive_name text not null,
    metadata_url text not null,
    expected_md5 varchar(64) not null,
    actual_md5 varchar(64),
    archive_type varchar(64) not null,
    status varchar(32) not null,
    failed_at timestamptz,
    attempt_token uuid,
    lease_expires_at timestamptz,
    file_size_bytes bigint not null,
    actual_size_bytes bigint,
    staged_archive_path text,
    staged_csv_path text,
    first_seen_at timestamptz not null,
    last_attempt_at timestamptz,
    completed_at timestamptz,
    attempt_count integer not null default 0,
    last_error_code varchar(64),
    last_error_retryable boolean,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint fk_ingestion_archives_run
        foreign key (run_id) references ingestion_runs (id),
    constraint uq_ingestion_archives_run_type
        unique (run_id, archive_type),
    constraint ck_ingestion_archives_type
        check (archive_type in ('TRANSLATION_EVENTS', 'TRANSLATION_MENTIONS')),
    constraint ck_ingestion_archives_status
        check (status in ('DISCOVERED', 'PROCESSING', 'FAILED', 'STAGED')),
    constraint ck_ingestion_archives_expected_md5
        check (expected_md5 ~ '^[0-9a-f]{32}$'),
    constraint ck_ingestion_archives_actual_md5
        check (actual_md5 is null or actual_md5 ~ '^[0-9a-f]{32}$'),
    constraint ck_ingestion_archives_size
        check (file_size_bytes > 0 and (actual_size_bytes is null or actual_size_bytes > 0)),
    constraint ck_ingestion_archives_attempt_count
        check (attempt_count >= 0),
    constraint ck_ingestion_archives_lease
        check (
            (attempt_token is null and lease_expires_at is null)
            or
            (attempt_token is not null and lease_expires_at is not null)
        ),
    constraint ck_ingestion_archives_failure_complete
        check (
            (last_error_code is null and failed_at is null
                and last_error_retryable is null)
            or
            (last_error_code is not null and failed_at is not null
                and last_error_retryable is not null)
        ),
    constraint ck_ingestion_archives_staged_artifacts
        check (
            status <> 'STAGED'
            or
            (actual_size_bytes is not null and actual_md5 is not null
                and actual_size_bytes = file_size_bytes and actual_md5 = expected_md5
                and staged_archive_path is not null and staged_csv_path is not null)
        ),
    constraint ck_ingestion_archives_status_state
        check (
            (
                status = 'DISCOVERED'
                and attempt_count = 0
                and last_attempt_at is null
                and attempt_token is null and lease_expires_at is null
                and last_error_code is null
                and completed_at is null
                and actual_size_bytes is null and actual_md5 is null
                and staged_archive_path is null and staged_csv_path is null
            )
            or
            (
                status = 'PROCESSING'
                and attempt_count > 0
                and last_attempt_at is not null
                and attempt_token is not null and lease_expires_at is not null
                and last_error_code is null
                and completed_at is null
                and actual_size_bytes is null and actual_md5 is null
                and staged_archive_path is null and staged_csv_path is null
            )
            or
            (
                status = 'FAILED'
                and attempt_count > 0
                and last_attempt_at is not null
                and attempt_token is null and lease_expires_at is null
                and last_error_code is not null
                and completed_at is null
                and actual_size_bytes is null and actual_md5 is null
                and staged_archive_path is null and staged_csv_path is null
            )
            or
            (
                status = 'STAGED'
                and attempt_count > 0
                and last_attempt_at is not null
                and attempt_token is null and lease_expires_at is null
                and last_error_code is null
                and completed_at is not null
                and actual_size_bytes is not null and actual_md5 is not null
                and staged_archive_path is not null and staged_csv_path is not null
            )
        )
);

create index ix_ingestion_runs_status
    on ingestion_runs (status);

create index ix_ingestion_runs_source_update_time
    on ingestion_runs (source_update_time);

create index ix_ingestion_archives_status
    on ingestion_archives (status);

create index ix_ingestion_archives_archive_type
    on ingestion_archives (archive_type);

create index ix_ingestion_archives_first_seen_at
    on ingestion_archives (first_seen_at);

create index ix_ingestion_archives_lease_expires_at
    on ingestion_archives (lease_expires_at)
    where status = 'PROCESSING';
